#JLJ
language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Software/i2/Teensy3.2ADCi2t/Teensy3.2ADCi2t.ino

install:
    - pip install -U platformio
#AirDC
    - wget http://www.basicairdata.eu/temp/AirDC.zip -O /tmp/airdc_source.zip
    - unzip /tmp/airdc_source.zip -d /tmp/
#I2C Lib with support of the second bus
    - wget http://www.basicairdata.eu/temp/i2c_t3-master.zip  -O /tmp/i2c_t3-master.zip
    - unzip /tmp/i2c_t3-master -d /tmp/
#SSC
    - wget http://www.basicairdata.eu/temp/SSC.zip -O /tmp/SSC.zip
    - unzip /tmp/SSC -d /tmp/
script:
    - platformio ci --lib="." --lib="/tmp/AirDC" --lib="/tmp/i2c_t3-master" --lib="/tmp/SSC1" --lib="/tmp/SSC" --board=teensy31
#- arduino --verify --board ${BOARD} $PWD/test/Blink/Blink.ino
